### ISSUE TITLE
Inner most wrapping div cannot be styled

### ISSUE THREAD

**Issue by darcyadams** [jcoreio/react-view-slider#4]
Each child component of the view slider is wrapped in a `div` element that receives a hard coded inline style of `width: '100%'`. This is problematic in certain layouts. The reason being that with no height constraint (or ability to add one) this `div` will grow to the size of its content. This prevents the child component from being able to fill its parent (ie height of 100%) and also have a scrolling element unless the developer is willing to put a fixed pixel height on them. 
Would you consider adding another optional inline style prop to allow styles to be added to this `div`?

```js
return (
      <div
        key={index}
        style={prefixer.prefix(style)}
        ref={c => (this.views[index] = c)}
      >
        <div style={{ width: '100%' }}> // <--- make this prop based?
```

**Comment by jedwards1211** [comment]
Sure, that's a good point.   Also, can you think of a good shortcut prop name for what you're trying to do?

**Comment by jedwards1211** [comment]
@darcyadams does `innerWrappingDivStyle` sound good?

**Comment by darcyadams** [comment]
@jedwards1211 thanks for the quick reply. 

yeah, `innerWrappingDivStyle` sounds perfect. `fillParent` seems like a great option for those working in an absolutely positioned layout. I'm currently working in an app laid out with flexbox, so `fillParent` just causes the view-slider to expand to the full window size, which does not work in this case.

**Comment by jedwards1211** [comment]
right, I wish there could be more of a magic one-size-fits-all solution but I sure can't think of one.  I'll merge that PR

**Comment by darcyadams** [comment]
thanks @jedwards1211 you win the award for most responsive project maintainer ever! 🏆

**Comment by darcyadams** [comment]
any chance you could quickly add support in `react-router-drilldown` for this prop? 🙏

**Comment by jedwards1211** [comment]
ah yes, that was on the back of my mind, cool that you're using that too!
