### ISSUE TITLE
keepViewsMounted breaks the view

### ISSUE THREAD

**Issue by baatten** [jcoreio/react-view-slider#52]
with keepViewsMounted enabled the slider breaks after first slide change.

the results is a blank slide.

any ideas?

**Comment by jedwards1211** [comment]
shoot, https://github.com/jcoreio/react-view-slider/commit/7f5d199ba3c4e660b78d5cdbd943a47daa99019d may have broken it.  Let me debug

**Comment by jedwards1211** [comment]
Hmmm, I haven't been able to reproduce yet by tweaking the `SignupDemo`, can you show me some code?

**Comment by baatten** [comment]
I think it was our own bug. so we can close this.
